language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t rook500/frontend-production-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true rook500/frontend-production-workflow npm run test